In [1]:
import pandas as pd

In [8]:
files = pd.read_csv('fl_date,mkt_unique_carrier,branded_code_', header=0)

In [9]:
files.head(5)

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
0,2019-12-31,WN,WN,WN,3762,WN,N553WN,3762,12889,LAS,...,1076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-12-31,WN,WN,WN,6677,WN,N200WN,6677,12889,LAS,...,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-12-31,WN,WN,WN,4908,WN,N8526W,4908,12889,LAS,...,1371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-12-31,WN,WN,WN,1783,WN,N8568Z,1783,12889,LAS,...,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-12-31,WN,WN,WN,1160,WN,N282WN,1160,12889,LAS,...,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
files.columns

Index(['fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier',
       'mkt_carrier_fl_num', 'op_unique_carrier', 'tail_num',
       'op_carrier_fl_num', 'origin_airport_id', 'origin', 'origin_city_name',
       'dest_airport_id', 'dest', 'dest_city_name', 'crs_dep_time', 'dep_time',
       'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in',
       'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled',
       'cancellation_code', 'diverted', 'dup', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'flights', 'distance',
       'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay',
       'late_aircraft_delay', 'first_dep_time', 'total_add_gtime',
       'longest_add_gtime', 'no_name'],
      dtype='object')

In [12]:
files.shape

"CARRIER_DELAY, WEATHER_DELAY, NAS_DELAY, SECURITY_DELAY, LATE_AIRCRAFT_DELAY"

(10, 42)

In [ ]:
files.columns == ['fl_date','mkt_carrier','mkt_carrier_fl_num',
                  'op_unique_carrier','op_carrier_fl_num', 'origin_airport_id',
                 'origin','origin_city_name','dest_airport_id', 'dest','dest_city_name',
                  'dep_time','wheels_off','wheels_on','arr_delay', 'cancelled',
                  'diverted','dup','flights']